/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IForwardRequest {
  export type PlaySessionStruct = {
    authorized: PromiseOrValue<string>;
    expiresAt: PromiseOrValue<BigNumberish>;
  };

  export type PlaySessionStructOutput = [string, BigNumber] & {
    authorized: string;
    expiresAt: BigNumber;
  };
}

export interface EssentialPlaySessionInterface extends utils.Interface {
  functions: {
    "createSession(address,uint256)": FunctionFragment;
    "createSignedSession(address,uint256)": FunctionFragment;
    "getSession(address)": FunctionFragment;
    "invalidateSession()": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "permissionlessSessions()": FunctionFragment;
    "setTrustedForwarder(address)": FunctionFragment;
    "verifyAuthorization(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createSession"
      | "createSignedSession"
      | "getSession"
      | "invalidateSession"
      | "isTrustedForwarder"
      | "owner"
      | "permissionlessSessions"
      | "setTrustedForwarder"
      | "verifyAuthorization"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createSession",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createSignedSession",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSession",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidateSession",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permissionlessSessions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedForwarder",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAuthorization",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSignedSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSession", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "invalidateSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permissionlessSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAuthorization",
    data: BytesLike
  ): Result;

  events: {
    "Session(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Session"): EventFragment;
}

export interface SessionEventObject {
  owner: string;
  authorized: string;
  length: BigNumber;
}
export type SessionEvent = TypedEvent<
  [string, string, BigNumber],
  SessionEventObject
>;

export type SessionEventFilter = TypedEventFilter<SessionEvent>;

export interface EssentialPlaySession extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EssentialPlaySessionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createSignedSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getSession(
      authorizer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IForwardRequest.PlaySessionStructOutput]>;

    invalidateSession(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    permissionlessSessions(overrides?: CallOverrides): Promise<[boolean]>;

    setTrustedForwarder(
      trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyAuthorization(
      signer: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  createSession(
    authorized: PromiseOrValue<string>,
    length: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createSignedSession(
    authorized: PromiseOrValue<string>,
    length: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getSession(
    authorizer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IForwardRequest.PlaySessionStructOutput>;

  invalidateSession(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isTrustedForwarder(
    forwarder: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  permissionlessSessions(overrides?: CallOverrides): Promise<boolean>;

  setTrustedForwarder(
    trustedForwarder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyAuthorization(
    signer: PromiseOrValue<string>,
    beneficiary: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    createSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createSignedSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getSession(
      authorizer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IForwardRequest.PlaySessionStructOutput>;

    invalidateSession(overrides?: CallOverrides): Promise<void>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    permissionlessSessions(overrides?: CallOverrides): Promise<boolean>;

    setTrustedForwarder(
      trustedForwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyAuthorization(
      signer: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Session(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      authorized?: PromiseOrValue<string> | null,
      length?: PromiseOrValue<BigNumberish> | null
    ): SessionEventFilter;
    Session(
      owner?: PromiseOrValue<string> | null,
      authorized?: PromiseOrValue<string> | null,
      length?: PromiseOrValue<BigNumberish> | null
    ): SessionEventFilter;
  };

  estimateGas: {
    createSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createSignedSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getSession(
      authorizer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invalidateSession(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    permissionlessSessions(overrides?: CallOverrides): Promise<BigNumber>;

    setTrustedForwarder(
      trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyAuthorization(
      signer: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createSignedSession(
      authorized: PromiseOrValue<string>,
      length: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getSession(
      authorizer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invalidateSession(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    permissionlessSessions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTrustedForwarder(
      trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyAuthorization(
      signer: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
